export const createUserTableQuery=`
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) UNIQUE NOT NULL,
  google_id VARCHAR(255) UNIQUE ,
  password VARCHAR(255),
  picture VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  last_login TIMESTAMP,
  CONSTRAINT CHK_AUTH_METHOD CHECK (google_id IS NOT NULL OR password IS NOT NULL)
);
`;